# Generated by Django 5.0.6 on 2024-06-28 19:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilitarInv', models.BooleanField(default=True, verbose_name='Habilitar Formulario')),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=100)),
                ('plan', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Modalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TutorExterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InvCientifica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Agregar Titulo')),
                ('slug', models.SlugField(unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField(blank=True, verbose_name='Agregar una Descripcion')),
                ('documentacion', models.FileField(blank=True, null=True, upload_to='documento/proyecto', verbose_name='Agregar Documentacion')),
                ('destacado', models.BooleanField(default=True, verbose_name='Destacar Formulario')),
                ('estado', models.CharField(choices=[('Aprobado', 'Aprobado'), ('Pendiente', 'Pendiente'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario relacionado')),
                ('modalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seg_Mod_Graduacion.modalidad', verbose_name='Seleccione Una Modalidad')),
            ],
        ),
        migrations.CreateModel(
            name='ComentarioInvCientifica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(max_length=1000, verbose_name='Ingrese Comentario Retroalimentativo')),
                ('fecha_post', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('proyecto_relacionado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seg_Mod_Graduacion.invcientifica')),
            ],
            options={
                'ordering': ['-fecha_post'],
            },
        ),
        migrations.CreateModel(
            name='PerfilProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Agregar Titulo')),
                ('slug', models.SlugField(unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField(blank=True, verbose_name='Agregar una Descripcion')),
                ('documentacion', models.FileField(blank=True, null=True, upload_to='documento/proyecto', verbose_name='Agregar Documentacion')),
                ('estado', models.CharField(choices=[('Aprobado', 'Aprobado'), ('Pendiente', 'Pendiente'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=10)),
                ('modalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seg_Mod_Graduacion.modalidad', verbose_name='Seleccione Una Modalidad')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario relacionado')),
            ],
        ),
        migrations.CreateModel(
            name='ComentarioPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(max_length=1000, verbose_name='Ingrese Comentario Retroalimentativo')),
                ('fecha_post', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('proyecto_relacionado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='Seg_Mod_Graduacion.perfilproyecto')),
            ],
            options={
                'ordering': ['-fecha_post'],
            },
        ),
        migrations.CreateModel(
            name='ProyectoFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('slug', models.SlugField(unique=True)),
                ('resumen', models.TextField(max_length=500)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('documentacion', models.FileField(blank=True, null=True, upload_to='documento/proyecto', verbose_name='Agregar Documentacion')),
                ('estado', models.CharField(choices=[('Aprobado', 'Aprobado'), ('Pendiente', 'Pendiente'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=10)),
                ('modalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seg_Mod_Graduacion.modalidad')),
                ('tribunales', models.ManyToManyField(blank=True, limit_choices_to={'groups__name': 'Docentes'}, related_name='tribunales', to=settings.AUTH_USER_MODEL)),
                ('tutor', models.ForeignKey(limit_choices_to={'groups__name': 'Docentes'}, on_delete=django.db.models.deletion.CASCADE, related_name='tutor_final', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario relacionado')),
                ('tutor_externo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Seg_Mod_Graduacion.tutorexterno')),
            ],
        ),
    ]
