# Generated by Django 5.0.6 on 2024-06-30 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Seg_Mod_Graduacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invcientifica',
            old_name='descripcion',
            new_name='invdescripcion',
        ),
        migrations.RenameField(
            model_name='invcientifica',
            old_name='destacado',
            new_name='invdestacado',
        ),
        migrations.RenameField(
            model_name='invcientifica',
            old_name='documentacion',
            new_name='invdocumentacion',
        ),
        migrations.RenameField(
            model_name='invcientifica',
            old_name='estado',
            new_name='investado',
        ),
        migrations.RenameField(
            model_name='invcientifica',
            old_name='fecha_creacion',
            new_name='invfecha_creacion',
        ),
        migrations.RenameField(
            model_name='invcientifica',
            old_name='modalidad',
            new_name='invmodalidad',
        ),
        migrations.RenameField(
            model_name='invcientifica',
            old_name='titulo',
            new_name='invtitulo',
        ),
    ]
