# Generated by Django 5.0.6 on 2024-06-30 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Seg_Mod_Graduacion', '0002_rename_descripcion_invcientifica_invdescripcion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentarioinvcientifica',
            options={'ordering': ['-invfecha_post']},
        ),
        migrations.AlterModelOptions(
            name='comentarioperfil',
            options={'ordering': ['-perfecha_post']},
        ),
        migrations.RenameField(
            model_name='comentarioinvcientifica',
            old_name='comentario',
            new_name='invcomentario',
        ),
        migrations.RenameField(
            model_name='comentarioinvcientifica',
            old_name='fecha_post',
            new_name='invfecha_post',
        ),
        migrations.RenameField(
            model_name='comentarioinvcientifica',
            old_name='proyecto_relacionado',
            new_name='invproyecto_relacionado',
        ),
        migrations.RenameField(
            model_name='comentarioperfil',
            old_name='comentario',
            new_name='percomentario',
        ),
        migrations.RenameField(
            model_name='comentarioperfil',
            old_name='fecha_post',
            new_name='perfecha_post',
        ),
        migrations.RenameField(
            model_name='comentarioperfil',
            old_name='proyecto_relacionado',
            new_name='perproyecto_relacionado',
        ),
        migrations.RenameField(
            model_name='perfilproyecto',
            old_name='descripcion',
            new_name='perdescripcion',
        ),
        migrations.RenameField(
            model_name='perfilproyecto',
            old_name='documentacion',
            new_name='perdocumentacion',
        ),
        migrations.RenameField(
            model_name='perfilproyecto',
            old_name='estado',
            new_name='perestado',
        ),
        migrations.RenameField(
            model_name='perfilproyecto',
            old_name='fecha_creacion',
            new_name='perfecha_creacion',
        ),
        migrations.RenameField(
            model_name='perfilproyecto',
            old_name='modalidad',
            new_name='permodalidad',
        ),
        migrations.RenameField(
            model_name='perfilproyecto',
            old_name='titulo',
            new_name='pertitulo',
        ),
    ]
