# Generated by Django 5.0.6 on 2024-06-28 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Seg_Mod_Graduacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Titulado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio_ingreso', models.IntegerField()),
                ('periodo_ingreso', models.CharField(max_length=50)),
                ('anio_egreso', models.IntegerField()),
                ('periodo_egreso', models.CharField(max_length=50)),
                ('numero_acta', models.CharField(max_length=50)),
                ('nota', models.FloatField()),
                ('proyecto_final', models.OneToOneField(limit_choices_to={'estado': 'Aprobado'}, on_delete=django.db.models.deletion.CASCADE, to='Seg_Mod_Graduacion.proyectofinal')),
                ('usuario', models.OneToOneField(limit_choices_to={'estado': True, 'groups__name': 'Estudiantes'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
