# Generated by Django 5.0.6 on 2024-06-29 15:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Repositorio_Titulados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titulado',
            name='anio_egreso',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='titulado',
            name='anio_ingreso',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='titulado',
            name='nota',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='titulado',
            name='periodo_egreso',
            field=models.IntegerField(choices=[(1, '1'), (2, '2')]),
        ),
        migrations.AlterField(
            model_name='titulado',
            name='periodo_ingreso',
            field=models.IntegerField(choices=[(1, '1'), (2, '2')]),
        ),
    ]
